### ISSUE TITLE
Is it possible to support SQL Compact 4.0?

### ISSUE THREAD

**Issue by mandm-pt** [IdentityServer/IdentityServer3.EntityFramework#102]
I'm trying to use IdentityServer3 with SQL Compact 4.0, I added IdentityServer3.EntityFramework and IdentityServer3.Admin.EntityFramework but I got an error because of Expiration property existent in ScopeSecret and ClientSecret types. If I change both to DateTime, everything seems to work as expected and the database is created.

Is it possible to add support to SQL Compact? Does this make sense?
In my case I don't expect to have a big database and I prefer to don't have dependency of a service.

**Comment by brockallen** [comment]
Well, it sounds like Sql Compact doesn't support the right data types. You'd have to do some mapping I guess.

**Comment by mandm-pt** [comment]
Exactly, the error is because of unsupported type, in this case DateTimeOffset. 
But my question is more about if it make sense to have support to this in your library? If yes I'm happy to implement the change, if not why. 

Thanks

**Comment by brockallen** [comment]
At the time we built it, the date time offset worked fine for what we targeted. As for why I'm hesitant to add it, I think it'd be a breaking change and potentially cause disruption for existing deployments.
