### ISSUE TITLE
Port this project to .Net Core and support IdentityServer4

### ISSUE THREAD

**Issue by galvesribeiro** [IdentityServer/IdentityServer3.EntityFramework#111]
Hello,

Is there any effort already being made to port this to .Net Core and support IdentityServer4?

If there isn't, can you guys create the IdentityServer4.EntityFramework repo so I can work on the port and make PRs to there?

Thanks!
Best regards,
Gutemberg

CC: @leastprivilege

**Comment by leastprivilege** [comment]
thanks! @brockallen is the PM for that ;)

**Comment by brockallen** [comment]
This repo is the one backing IdSvr3. If anything we'd have a new repo for ED for IdSvr4.

**Comment by galvesribeiro** [comment]
@brockallen I understood that. Can a repo be created under the IdSrv 4 for that so we can start contributing the port?

**Comment by brockallen** [comment]
Yes, I can start something like this soon...

**Comment by brockallen** [comment]
I'll close this since we'll track this in a new repo.

**Comment by galvesribeiro** [comment]
@brockallen is there a new issue, PR or repo for that?

**Comment by brockallen** [comment]
No, but it's certainly something we're considering as we work on IdSvr4. This repo won't be the successor.

**Comment by galvesribeiro** [comment]
ok, so for now, no EF Core support. Understood. Thanks

**Comment by brockallen** [comment]
"as of now" :)
