### ISSUE TITLE
schema do __MigrationHistory 

### ISSUE THREAD

**Issue by GustavoAmerico** [IdentityServer/IdentityServer3.EntityFramework#114]
Porque a tabela __MigrationHistory nunca fica dentro do schema definido na inicialização do contexto?
Ao utilizar o código abaixo o EF cria a tabela __MigrationHistory  no schema dbo, como fazer essa tabela ser criada no schema que eu defini ?

`using (var scopeDb = new ScopeConfigurationDbContext(connString, schema))`

**Comment by brockallen** [comment]
Use migrations.
