### ISSUE TITLE
How to control the number of times a day to get accesstoken ？

### ISSUE THREAD

**Issue by zhouyongtao** [IdentityServer/IdentityServer3.EntityFramework#117]
How to control the number of times a day to get accesstoken ？

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
