### ISSUE TITLE
Package is currently not compatible with AutoMapper 6.0.2

### ISSUE THREAD

**Issue by kwaxi** [IdentityServer/IdentityServer3.EntityFramework#130]

**Comment by brockallen** [comment]
Out of curiosity, what broke?

**Comment by kwaxi** [comment]
I tried to upgrade AutoMapper to version 6 in a project where I used IdSrv3 and IdSrv3.Ef and it didn't work. I'll give you more detailed info after the holiday weekend.

**Comment by brockallen** [comment]
No worries -- don't bother. It was only mild curiosity :)

**Comment by kwaxi** [comment]
Sorry for bothering, I couldn't reproduce it anymore, but I opened the issue after getting some exceptions regarding version of the AutoMapper assembly on load ... seem's the reason for that was something else.

**Comment by brockallen** [comment]
So we should close the PR then too?

**Comment by kwaxi** [comment]
Sure, it only would force users to upgrade without any need.
