### ISSUE TITLE
Option to change the connectionstring on runtime

### ISSUE THREAD

**Issue by hagailuger** [IdentityServer/IdentityServer3.EntityFramework#132]
Hi,
When setting (in the startup) the `ConnectionString` for `EntityFrameworkServiceOptions` and then registering it in the `IdentityServerServiceFactory`- it stays this way forever. 
We are using AlwaysOn functionality on SQL, So we need a way to inform `IdentityServer` that the `ConnectionString `was changed

**Comment by brockallen** [comment]
If the options is in DI as a singleton, can't you just change the object's property?

**Comment by hagailuger** [comment]
Thanks! 
I wasn't aware it's an option. Testing and would let you know.

**Comment by hagailuger** [comment]
working. thanks!
