### ISSUE TITLE
Feature Request: Admin interface

### ISSUE THREAD

**Issue by adrianohck** [IdentityServer/IdentityServer3.EntityFramework#46]
I have installed Identity Server 3 with Entity Framework. That's fine, it is working.

Now, I have to configure a new client to access it and I didn't find any repository that I could install in order to include a new client via web interface.

Do I have to include this new client direct into the database, in the tables "Clients" and "ClientRedirectUris"?

**Comment by brockallen** [comment]
We have a repo here for that: https://github.com/IdentityServer/IdentityServer3.Admin

It's still a work in progress.
