### ISSUE TITLE
Model Names Too long (part II)

### ISSUE THREAD

**Issue by LeandroPT** [IdentityServer/IdentityServer3.EntityFramework#47]
Hello,

This has already occurred with issue #31.
The problem now has to be with the implementation of issue #43 with the property name UpdateAccessTokenClaimsOnRefresh, which is longer than 30 characters on Oracle, and will not work.

**Comment by brockallen** [comment]
Do you mind writing a unit test that we can run to check those constraints and then submit it as a PR? That way we won't run into this in the future.

**Comment by brockallen** [comment]
Any progress?

**Comment by brockallen** [comment]
Did you ever work around 4this issue?

**Comment by brockallen** [comment]
I added a unit test to verify the length of the entity properties. I'm hesitant to change the EF code, as that will be a breaking change. Thoughts?

**Comment by brockallen** [comment]
Ok, I renamed the two offending columns and re-enabled the unit test to check those lengths.
