### ISSUE TITLE
ClaimsPrincipalConverter potential problem when deserializing ClaimsPrincipal

### ISSUE THREAD

**Issue by 20John22** [IdentityServer/IdentityServer3.EntityFramework#48]
In Thinktecture.IdentityServer.Core solution ClaimsIdentity is created using such statement
```C#
var id = new ClaimsIdentity(claims, authenticationType, Constants.ClaimTypes.Name, Constants.ClaimTypes.Role);
```
whereas in Thinktecture.IdentityServer.EntityFramework for ClaimsPrincipalConverter is used such statement
```C#
var id = new ClaimsIdentity(claims, source.AuthenticationType);
```
For that reason Name property of ClaimsPrincipal is null. I believe it should have value of claim with type name.

**Comment by brockallen** [comment]
So you're getting `Name` of `null` somewhere in your code (perhaps in the user service) due to this?

**Comment by 20John22** [comment]
Nope it doesn't cause any errors right now. I had that error because I've started reusing that converter.

**Comment by brockallen** [comment]
Ah ok. I was trying to determine where it mattered. I think it'll be ok to make this change if it help you.

**Comment by 20John22** [comment]
Would be great. Thanks.

**Comment by brockallen** [comment]
Do you want to send a PR for this? It'll get done sooner if you do it :)

**Comment by brockallen** [comment]
Ok, this was quick -- I added it on dev.
