### ISSUE TITLE
Support for EF7 and ASP.Net Identity v3

### ISSUE THREAD

**Issue by rajajhansi** [IdentityServer/IdentityServer3.EntityFramework#49]
I've successfully integrated IdentityServer3 2.0.0 beta dev into my new ASP.NET 5 application using InMemoryStore example in the awesome IdentityServer3.Samples project. Instead of hard coding the clients, scopes etc., I'd prefer to load them from SQL tables using the Factory property. I was able to use the Migrations provided in the Samples project but now I need to make it work with EF7. So, I've run the migrations using EF 6.1 and then used "dnx . ef revEng" to reverseEngineer the models into EF7. I totally understand that ASP.NET 5 is in its early stages and so is EF7. Do you have plans to support EF7? I have the same issue with ASP.NET Identity as well since the examples are using ASP.NET Identity 2.x whereas the ASP.NET 5 includes ASP.NET Identity v3. What is your recommendation to wire ASP.NET Identity v3 into IdentityServer3 2.0.0 beta dev build? I really appreciate any help or direction to make this integration working.

**Comment by brockallen** [comment]
We have no immediate plans for EF7. We will eventually, but no time soon.
