### ISSUE TITLE
Database setup SQL script

### ISSUE THREAD

**Issue by skuvnar** [IdentityServer/IdentityServer3.EntityFramework#50]
Hi there,
Just wondering if there are any setup SQL scripts that could be used in a environment where I don't have permissions to create databases or tables.

I noticed membership reboot had a migration sql script, but could not find a similar one here. 
Thanks

**Comment by brockallen** [comment]
You're expected to use migrations. You can do this from your dev environment and have that generate a SQL script, which you can then hand over to your DBA. Check the EF documentation.
