### ISSUE TITLE
AddOrUpdate for Clients

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer3.EntityFramework#54]
We've set up IdSrv3 and EF model. However, when running seed method for client db context, I keep seeing duplicate entries after a few runs. First run, all clients inserted. Subsequent runs, it's like one of the clients randomly gets inserted over and over. Even Client.Id values get switched in the db table. What is wrong here?

Seed code is simple:

            var clients = new List<Client>
            {
               new Client { ClientId = "c1", ClientName = "C1",...
               new Client { ClientId = "c2", ClientName = "C2",...
               new Client { ClientId = "c3", ClientName = "C3",...
            };
 
             foreach (var client in clients)
            {
                context.Clients.AddOrUpdate(c => c.ClientId, client.ToEntity());

                // also tried:
                //context.Clients.AddOrUpdate(c => c.Id, client.ToEntity());
                //context.Clients.AddOrUpdate(c => new { c.Id, c.ClientId }, client.ToEntity());
            }

            SaveChanges(context);

Thanks

**Comment by brockallen** [comment]
`ClientId` is the logical key, but the `Id` is the real primary key. I'm not sure the `AddOrUpdate` will know how to deal with that.

**Comment by snothub** [comment]
Yeah, it fell short there, had to do it manually. Thanks anyway.
