### ISSUE TITLE
In the dev version, which Client should be used?

### ISSUE THREAD

**Issue by tofutim** [IdentityServer/IdentityServer3.EntityFramework#55]
Client shows up in IS3.EntityFramework.Entities and IS3.Core.Models. In the Samples, it does show up under Core.Models.

**Comment by brockallen** [comment]
Those re 2 different clients. One in the IdSvr core is the data structure used by the IdSvr engine. The one in the EF library is the entity for modeling persistence w/ EF.

**Comment by tofutim** [comment]
So, if I am using EF, I should refer to the one from the EF library, rather
than the one from IdSvr core.

Should the Clients.cs (and others) be modified in
IdentityServer3.Samples\source\EntityFramework\SelfHost\Config to reflect
this?

**Comment by tofutim** [comment]
Scratch that, I now see there is a ToEntity function, which changes Client
to the EntityFramework Client.

**Comment by dotnetrules** [comment]
Hi all, I have a very similar question as @tofutim so thought it best to post here.

I've basically taken the AspNetIdentity_2fa sample project (for the extensibility with IdMgr and AspId) as a starting point and now I would like to continue using EF to persist Clients/Scopes/etc etc. 

I too have been looking at the EF sample project (IdentityServer3.Samples-master\source\EntityFramework) for guidance on how to best achieve this.  Just like @tofutim I too was thinking of using Clients.cs and related bits etc to use the AspNetIdentity_2fa project. Is this best approach? I've read all the doco, watch all the videos so I assume it is? 

I'm just wondering if there is any mapping between AspId and EF schemas? reason I ask is I'm just trying to work out if AspId needs to live in the same sql server db as persisted clients/scopes etc. 

Is there already a UI to manage EF clients and other operational data beside what IdMgr offers out the box?

Thanks Paul

**Comment by tofutim** [comment]
Dear Paul,

If you look, the Factory creates the right kind of Client (the EF client).
The example (in Factor.cs) takes Model.Client and turns it into an
EF.Client using ToEntity()

                if (!db.Clients.Any())

                {

                    foreach (var c in clients)

                    {

                        var e = c.ToEntity();

                        db.Clients.Add(e);

                    }

                    db.SaveChanges();

                }

**Comment by dotnetrules** [comment]
Thanks @tofutim 

That's what I was looking to do in the AspNetIdentity_2fa sample project so I think I will give it a go. I just question how this ties in with AspNetIdentity library, if at all, in terms of relationships between the two different table sets, for example any primary/foreign key constraints etc.

Cheers :+1:

**Comment by brockallen** [comment]
AspNetIdentity is unrelated to the IdSvr EF library. See the docs: https://identityserver.github.io/Documentation/docs/ef/overview.html
