### ISSUE TITLE
Token.Expiry not Sql 2005 compatible

### ISSUE THREAD

**Issue by cwilliamson1980** [IdentityServer/IdentityServer3.EntityFramework#58]
Thought I would post a question to determine whether a decision was made to purposely support MSSQL 2008 and later.  I am having to support a minimum of MSSQL 2005 where datetimeoffset is not a supported type.  See https://msdn.microsoft.com/en-gb/library/bb630289.aspx

The entity *Token* has a property called *Expiry* of the .NET type DateTimeOffset.
See https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Entities/Token.cs#L42

Have you guys got experience with EF with how I can use this library against MSSQL 2005.

**Comment by brockallen** [comment]
I just saw an email saying Sql2005 end support is coming soon. I know that's unrelated to your question, but I thought I'd mention it.

**Comment by cwilliamson1980** [comment]
Yeah, you're right 12 April 2016.

**Comment by brockallen** [comment]
So I'd find out first if your company still needs/wants to work with Sql2005 before we try to do something in IdSvr. My gut feeling is that since we're already committed to DateTimeOffset that I don't foresee changing that.

**Comment by brockallen** [comment]
Any update?

**Comment by cwilliamson1980** [comment]
Yeah,  long story short is that I want this to work with Sql2005.  My initial thoughts are to fork this library locally and to map Token.Expiry to 2 columns (DateTimeUtc, Offset).  Any thoughts as to why Token.Expiry is a DateTimeOffset and not just a UTC DateTime?

**Comment by brockallen** [comment]
DateTimeOffset is the replacement for it -- it has a superset of features.

So yea, you'll have to map to Sql2005 and then map back to DateTimeOffSet for IdSvr. Sorry.

**Comment by mnaoumov** [comment]
Unofrunately, I have to support SQL Server 2005 as well. So I had to add a fix https://github.com/mnaoumov/IdentityServer3.EntityFramework/commit/6405f0e0cec94c36b61e1aa77580020bc33262ae
