### ISSUE TITLE
Question: How to Administrate?

### ISSUE THREAD

**Issue by dotnetrules** [IdentityServer/IdentityServer3.EntityFramework#59]
Hi all, this is perhaps a question for @brockallen and @leastprivilege 

I have been experimenting with this and it truly fits what we'd like to do. However the obvious question comes about as to how to manage the data, a web admin site would be fantastic. I see there are a couple of Admin projects for EF however these appear dead in the water, especially after trying to get them to work and after reading this issue and others:

https://github.com/IdentityServer/IdentityServer3.Admin/issues/15

So I was wondering if you are aware of any admin project out there that does work? and or if there is a road map for anything like this?  

If there's nothing :-( how do you both or anyone else manage the EF data in terms of doing CRUD like management for clients, claims, scopes etc etc...

"Truly appreciate" any advice you could offer :+1:

**Comment by brockallen** [comment]
We know it'd be nice to have an admin UI, but we just don't right now. This is mainly due to the lack of time. If you're interested in working on an OSS one, then let us know.

**Comment by dotnetrules** [comment]
Thanks for the info @brockallen 

Yes I'd be very happy to work on a OSS. I do need to build one, and if nothing existed I was originally looking to follow the same/similar design, pattern, convention, principles and architecture you've applied in your other projects with an embedded UI so it feels familiar to work with etc.

Look forward to your reply, thoughts, instructions etc.

Cheers :)

**Comment by kumoninotte** [comment]
May be I could also help. Please just let me know.

**Comment by brockallen** [comment]
I'm quite busy this week, but maybe we could meet on Friday in the gitter chat room and discuss?

**Comment by dotnetrules** [comment]
No worries. I'm located in Australia GMT+9.30
I work across a few different time zones inc GMT-5, I'll be available.
Cheers

**Comment by kumoninotte** [comment]
PDT Here (GMT-7). My schedule is very flexible.
please just let me know whenever you guys can do the meeting.

**Comment by brockallen** [comment]
Ah, sorry -- I got busy and totally forgot to look for you.

**Comment by dotnetrules** [comment]
Hi Brock, all good. I was hanging around the chat room, however I could see that you were busy pushing stuff out and didn't want to get in the way.  I'm available any time so I'll workaround you guys :+1: 

Cheers

**Comment by brockallen** [comment]
Closing since we started on the admin project.

**Comment by OutOfTouch** [comment]
How is this project going?

**Comment by brockallen** [comment]
Good question -- I need to check up on it :)
