### ISSUE TITLE
MySQL issues with ClientConfigurationDbContext

### ISSUE THREAD

**Issue by buybackoff** [IdentityServer/IdentityServer3.EntityFramework#62]
I know that EntityFramework doesn't work perfectly with non-MSSQL DBMSs, but I used to live with this pain and even managed to work with auto migrations in MySQL/Postgres... I haven't started to debug this issue yet, have just wired up the EF sample... It is mid-night Friday, so I will post it here for the record and I will debug it later.

A general thought is that DateTimeOffset is a bad structure everywhere outside .NET boundary and even inside .NET. The best practice is to store DateTime in UTC, and when it matters - a time zone separately. 

```
An exception of type 'System.Data.Entity.Core.MappingException' occurred in EntityFramework.dll but was not handled in user code

Additional information: Schema specified is not valid. Errors: 

(75,12) : error 2019: Member Mapping specified is not valid. The type 'Edm.DateTimeOffset[Nullable=True,DefaultValue=,Precision=]' of member 'Expiration' in type 'IdentityServer3.EntityFramework.ClientSecret' is not compatible with 'MySql.timestamp[Nullable=True,DefaultValue=,Precision=0]' of member 'Expiration' in type 'CodeFirstDatabaseSchema.ClientSecret'.
```

**Comment by brockallen** [comment]
Sounds like DateTimeOffset is not supported by MySQL.

**Comment by buybackoff** [comment]
There was one more same issue with `Token` class. I have made a quick fix - just changed DTO to DateTime in entities and customized DTO<->DT property mapping. Interestingly, everywhere DTO was used with `DTO.UtcNow`, so the full functionality of DTO is not used and effectively UTC time is used.

**Comment by brockallen** [comment]
So you're all set now?

**Comment by buybackoff** [comment]
Other than the pain of maintaining my own build vs NuGet, I am OK.

**Comment by brockallen** [comment]
Ok, sorry about that.

**Comment by Nicholi** [comment]
Would you consider implementing the changes to just use DateTime instead of DateTimeOffset?

It's true MySQL doesn't support DateTimeOffset, but when you think about it DateTimeOffset is a special type ONLY supported by MSSQL (it's not a standard SQL type). Not even Oracle has support for it. In the interest of making other backends usable (without everyone making their own forks) it would be simpler if it was just a DateTime. Not to mention UTC is being used anyways, why the Offset is necessary not sure.

**Comment by brockallen** [comment]
You make a compelling argument. I'd like to have some pressure on MSFT then to get this right, to be honest. @leastprivilege thoughts?

**Comment by leastprivilege** [comment]
@jageall made that change to better support MongoDb - maybe he can explain the rationale and options.
