### ISSUE TITLE
Bug refreshing token in IdentityServer3.EntityFramework RefreshTokenStore

### ISSUE THREAD

**Issue by johnsmith121245457878** [IdentityServer/IdentityServer3.EntityFramework#65]
Refresh token always expires.
Bugfix is as follows:

	    // Bugfix: this is incorrect because TokenRequestValidator determines whether the refresh token is expired as follows:
	    // if (refreshToken.CreationTime.HasExceeded(refreshToken.LifeTime))		
            // token.Expiry = DateTimeOffset.UtcNow.AddSeconds(value.LifeTime);
	    // The LifeTime is continuously incremented
            token.Expiry = value.CreationTime.AddSeconds(value.LifeTime);
            token.JsonCode = ConvertToJson(value);

**Comment by brockallen** [comment]
Sorry -- I just had time to look at this now. Should this issue be in the core repository (instead of this one)? I guess I don't see exactly how to repro the problem.

**Comment by brockallen** [comment]
Ok, I see -- yes, this was a bug if the refresh token was sliding. I fixed it on dev. Thanks!
