### ISSUE TITLE
Setting up Clients 

### ISSUE THREAD

**Issue by HaroonSaid** [IdentityServer/IdentityServer3.EntityFramework#66]
Hi,

It would have been useful to document that the secret is kept in base64encoding using utf8 (and not unicode), in other words

declare @bin varbinary(max)
declare @base64 nvarchar(max)
--set @bin = HashBytes('sha2_256', N'newsecret') -- Doesnt work
set @bin = HashBytes('sha2_256', 'newsecret') -- works 
select @base64=cast(N'' as xml).value('xs:base64Binary(xs:hexBinary(sql:variable("@bin")))', 'nvarchar(max)');
select @bin,@base64
update ClientSecrets set [Type]='SharedSecret', Value=@base64 where Id=1

The column is defined as nvarchar, so my assumption was that HashExtension to convert would use Unicode.

**Comment by brockallen** [comment]
Perhaps adding it here would be sufficient? 

https://identityserver.github.io/Documentation/docsv2/configuration/secrets.html
