### ISSUE TITLE
Token table not getting written to

### ISSUE THREAD

**Issue by danielwertheim** [IdentityServer/IdentityServer3.EntityFramework#67]
I have configured my OP for use with your EF provider for operational data and client & scopes.

```csharp
var efConfig = new EntityFrameworkServiceOptions
{
    ConnectionString = "test"
};

ConfigureClients(Clients.Get(), efConfig);
ConfigureScopes(Scopes.Get(), efConfig);

var factory = new IdentityServerServiceFactory()
factory.RegisterConfigurationServices(efConfig);
factory.RegisterOperationalServices(efConfig);
factory.UseInMemoryUsers(Users.Get());
```

Tables are generated and populated *except* the `Tokens` table. It is only generated but never inserted to. I was under the impression that once authenticated, the requested tokens e.g. `identity token` and `access token` would be persisted here.

When is data supposed to end up there?

**Comment by brockallen** [comment]
It depends on the flows and token types being used. Change a client to use a reference token and you'll see.

**Comment by jesus2509** [comment]
Which are the tokens types and flows that save the token information on the database ?

**Comment by sudipster** [comment]
I am also using id server3 with entityframework and only token that seems to get persisted is refresh tokens. I don't see any other tokens in the database.

**Comment by brockallen** [comment]
The types of tokens you see in the db depends how you use idsvr

-Brock

**Comment by sudipster** [comment]
@brockallen, I have tried using implicit, auth code n resource owner flows, but like I said only token that goes into the tokens table is refresh token. Should I not see access tokens or auth codes in tokens table as well or are they persisted somewhere else? I don't see any errors in the logs.

**Comment by sudipster** [comment]
Outputs from my logs look normal as well... This was an from auth code flow.  However, only token I see is of TokenType of '3' in the database.

Logs--
w3wp.exe Information: 0 : 2016-05-23 13:56:00.820 -05:00 [Information] Creating token response
w3wp.exe Information: 0 : 2016-05-23 13:56:00.821 -05:00 [Information] Processing authorization code request
2016-05-23 13:56:00.824 -05:00 [Debug] Creating access token
2016-05-23 13:56:00.828 -05:00 [Debug] Creating refresh token
2016-05-23 13:56:00.828 -05:00 [Debug] Setting an absolute lifetime: 2592000
2016-05-23 13:56:00.841 -05:00 [Debug] Creating JWT access token
2016-05-23 13:56:00.853 -05:00 [Debug] Creating identity token

**Comment by brockallen** [comment]
Codes are usually written and then exchanged (and thus deleted) fairly fast.

**Comment by sudipster** [comment]
That makes sense. But still not seeing the access tokens though.

**Comment by brockallen** [comment]
If they're JWTs then you're right -- those are not written either.

**Comment by sudipster** [comment]
Are you implying JWTs reside in memory only? If so, how do they get validated in production/load balanced server scenario?  Thanks for your response Brock.

**Comment by brockallen** [comment]
JWts are self-contained and are validated by the signing cert from the STS. they don't need to be stored in the DB in the STS.

**Comment by sudipster** [comment]
That clears things up. Thanks a lot.

**Comment by luuksommers** [comment]
Was searching for the same thing, especially because we have some weird behavior in a Load Balanced scenario. 2 Api servers and 2 Identity servers, all cross connected sometimes fails (but I guess now that it has nothing to do with the persistent storage.
