### ISSUE TITLE
Defaults do not Match Documentation

### ISSUE THREAD

**Issue by raziellionheart** [IdentityServer/IdentityServer3.EntityFramework#69]
The default values of the entities do not match the defaults documented on the IdentityServer3 website. Since the defaults don't match, a lot of the examples on there are compromised.

I wrote an extension method in my solution to deal with this:

public static void SetDefaults(this IdentityServer3.EntityFramework.Entities.Client client)
        {
            client.Enabled = true;
            client.RequireConsent = true;
            client.AllowRememberConsent = true;
            client.Flow = Flows.Implicit;
            client.IdentityTokenLifetime = 300;
            client.AccessTokenLifetime = 3600;
            client.AuthorizationCodeLifetime = 300;
            client.AbsoluteRefreshTokenLifetime = 2592000;
            client.SlidingRefreshTokenLifetime = 1296000;
            client.RefreshTokenUsage = TokenUsage.ReUse;
            client.RefreshTokenExpiration = TokenExpiration.Absolute;
            client.AccessTokenType = AccessTokenType.Jwt;
            client.EnableLocalLogin = true;
            client.IdentityProviderRestrictions = new List<ClientIdPRestriction>();
            client.AlwaysSendClientClaims = false;
            client.PrefixClientClaims = true;
        }

**Comment by brockallen** [comment]
Good point. We do accept PRs :)

**Comment by leastprivilege** [comment]
PR?
