### ISSUE TITLE
3 db contexts

### ISSUE THREAD

**Issue by skivsoft** [IdentityServer/IdentityServer3.EntityFramework#70]
Hello,

May I ask is there any reason to use three different db contexts instead of one?

**Comment by skivsoft** [comment]
I would like to use IdSrv.EF in my project, and also I would like to keep it maintainable for future changes in IdSrv. So I inherits each of these 3 db contexts and create manual EF migrations in my derived db contexts. 

In this case after any future changes in IdServ's entites I shoud execute Add-Migration for all three db contexts in my project. For me is better to have only one db context.

Could I propose PR to do something like already done here [DbContextUserAccountRepository.cs](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot.Ef/DbContextUserAccountRepository.cs) to cover my case? or even maybe create an interfaces for the db contexts and pass through the interfaces to [ClientStore's constructor](https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Stores/ClientStore.cs#L30) instead of passing through concrete db context?

**Comment by brockallen** [comment]
Because not everyone needs or wants all three.

**Comment by skivsoft** [comment]
Could it be changed in the same way as in [MembershipReboot.Ef](https://github.com/brockallen/BrockAllen.MembershipReboot/tree/master/src/BrockAllen.MembershipReboot.Ef) using repositories and extensions for DBModelBuilder?

**Comment by brockallen** [comment]
What specifically did you have in mind?

**Comment by skivsoft** [comment]
It would be nice to have an option to use it in one context without changing 3 db contexts by default.

**Comment by brockallen** [comment]
Well, if you can prototype an approach that allows both, then we're open to PRs.

**Comment by skivsoft** [comment]
What do you think about PR #71 is it okay?

**Comment by brockallen** [comment]
Ok, I took a look and it seems fine -- I suppose you're doing your own single DbContext in your own code somewhere?

**Comment by brockallen** [comment]
Ok, I merged the PR. Thanks.
