### ISSUE TITLE
Any plan to EntityFramework 7?

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3.EntityFramework#74]
If stub a new repo I can work on it?

**Comment by mikeandersun** [comment]
We can host IdentityServer3 in APS.NET 5.
Can we have Entity Framework 7 data layer?

**Comment by brockallen** [comment]
You can build your own stores to use EF7 (or fork the EF repo and migrate that). Once you build it, let us know where we can link it from our docs.

**Comment by jarroda** [comment]
We have started an implementation for EF7.  It is pretty much a direct port of the EF6 provider.  It is mostly complete, but we just implemented it today, so its untested.  We will be taking contributions however.

**Comment by brockallen** [comment]
Ok, thanks @jarroda. I added you to the community addon page: https://identityserver.github.io/Documentation/docsv2/resources/community.html
