### ISSUE TITLE
Q: Best way to extend entities?

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3.EntityFramework#76]
Is there a recommended way to extend/customize entities while maintaining future compatibility?

**Comment by brockallen** [comment]
What's the requirement behind this?

**Comment by Peperud** [comment]
Toying with ways to handle multi tenancy in IdSrv3 backed by EF. In this case, it would/might make sense to have clients/apps be per tenant then. Naturally, a foreign key cleint->tenant  comes to mind...

A way I guess would be to have all the "extended" properties needed in a different entity/table with application enforced relation to the corresponding entity in IdSrv3.EF.

**Comment by brockallen** [comment]
Yea, it might be easier to inject a different store for the tenant in the request.
