### ISSUE TITLE
Version of IdentityServer3 referenced by package.configs no longer exists?

### ISSUE THREAD

**Issue by l33way** [IdentityServer/IdentityServer3.EntityFramework#83]
It looks like the version for identity server 3 (2.2.0-build00309)  referenced in all packages.configs no longer exists at myget. This causes restore to fail.

**Comment by brockallen** [comment]
I'll take a look. I probabaly need to update to what's on myget and then pin it.

**Comment by leastprivilege** [comment]
the release nuget should reference release depenencies

**Comment by brockallen** [comment]
And it does: https://www.nuget.org/packages/IdentityServer3.EntityFramework

**Comment by leastprivilege** [comment]
ah ok - so @l33way talks about the source code. oh well.

**Comment by brockallen** [comment]
Ok, fixed.
