### ISSUE TITLE
Invalid object name ScopeSecrets

### ISSUE THREAD

**Issue by mmihaylov** [IdentityServer/IdentityServer3.EntityFramework#84]
Hello, 

I am using IdentityServer v2.1.1 and IdentityServer3.EntityFramework v2.0.0. Today I decided to up upgrade to the latest versions which are IS3 - v2.2.3 and IS3.EF v2.2.0. After running the site I got an error

`Invalid object name 'dbo.ScopeSecrets'`

As far as I see this is relatively new object added to the EF extension. Is there a migration for it or any other suggestions how to update the database.

**Comment by mmihaylov** [comment]
OK.. I found this sample mentioned in another issue

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/EntityFramework

Can I use these migrations from the sample?

P.S. I thought that if there are any changes/migrations, they might be published in the documentation page of the EF extension.

**Comment by leastprivilege** [comment]
In EF, the consumer is responsible for managing the migrations (IOW you). 

You need to create the initial migration so EF can "calculate" the delta. We have an EF section in our docs as well (but this is really an EF topic)

**Comment by mmihaylov** [comment]
Yes, I was using the previous version of IS with EF and I had the initial migrations and all other additional (as specified in this section of the docs).

I will add the migration from the sample and I think this will solve the problem.
