### ISSUE TITLE
Update to latest AutoMapper 4.2

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer3.EntityFramework#88]
This issue: https://github.com/IdentityServer/IdentityServer3.EntityFramework/issues/72#issuecomment-180094260

**Comment by brockallen** [comment]
@martinlevington i pushed an update to MyGet with the AutoMapper 4.2 updates. Mind testing it for me to confirm that it's working?

**Comment by martinlevington** [comment]
Sure, do you have a link?

**Comment by brockallen** [comment]
Same as this: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/SelfHost%20%28Minimal%29/NuGet.config

**Comment by martinlevington** [comment]
Ok, I will test it later today

**Comment by martinlevington** [comment]
Hi, I can conform that the changes you added appear have fixed the issue. I have rerun through the tests that produced the issues yesterday and cannot reproduce the error. So it looks like the changes have fixed the issue.

Thanks.

**Comment by brockallen** [comment]
2.4.1 was just pushed to NuGet (and uses AutoMapper 4.2).
