### ISSUE TITLE
Not able to generate the token with this sample

### ISSUE THREAD

**Issue by UmeshSgh** [IdentityServer/IdentityServer3.EntityFramework#92]
Hi,

I have downloaded this sample and it is running fine. when try to generate the token to understand how all information are going to persist with db. Unfortunately, always getting "grant_invalid". 

Here is the code:
	var client = new TokenClient(
				"https://localhost:44333/core/connect/token",
				"roclient",
				"secret");

			return client.RequestResourceOwnerPasswordAsync("bob", "bob", "read write").Result;

Could you please correct me or suggest how I should invoke. I have configured one Identityserver using IUserservice and using similar syntax to get the access_token.

**Comment by brockallen** [comment]
I can't tell just from this. Check the logs in IdSvr.
