### ISSUE TITLE
Where I should manage token related information?

### ISSUE THREAD

**Issue by UmeshSgh** [IdentityServer/IdentityServer3.EntityFramework#93]
Hi,

I am not sure this is right place to post my issue or not. I am pretty new with Identityserver. 
Recently, I have configured one Identityserver server which is linked my usermanager database.
It is working as expected. 

Now, we want to little improvement and we have some concern regarding where to manage token related information. After going through this sample It seems I am right place.

Could you please suggest me some solution to this scenario. I am struggling a lot and at last posting here.
 
- How we should manage the token in case server reboot ? I mean, our requirement if access_token is already generated and life time is not yet expired. If our server got restarted then it should not re-generate the token and able to authenticate with old token.

Thanks a lot your kind help.

**Comment by brockallen** [comment]
Did you read the docs?

https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html
https://identityserver.github.io/Documentation/docsv2/ef/overview.html

**Comment by UmeshSgh** [comment]
Thanks brock for quick reply. Yes. I have gone through once. deployment one I could not understand everything like "If you are running in IIS, you need to synchronize machine keys".

Anothor link pointing the solution with help of Entityframework sample. This sample is excellent. Can we have some client application which is consuming the IdSrv. As I asked this question in other thread I am not able to request to access_token. I saw your reply I should look into log. 

in sample's web.config log file path is "c:\logs\IdentityServer3.EntityFramework.log". I don't see any file generated here.
   <listeners>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="c:\logs\IdentityServer3.EntityFramework.log" />
        <remove name="Default" />
      </listeners>
I read this.
http://leastprivilege.com/2015/10/22/identityserver3-logging-monitoring-using-serilog-and-seq/

This is very informative and interesting. My situation is I am new in this framework and need to lean a lot. So, not able view the log file. It will be great help if you guide me how to debug IdSrv then I may find solution myself.

Thanks!

**Comment by brockallen** [comment]
> Synchronizing machine key - Please elaborate. Is is machine.config which manage all IIS's application of something else? 

This is standard ASP.NET key management. These are the basics of building web application security -- I'd suggest researching this on the MSDN forums. 

> I saw your reply that I should look into log. 

Here's how to configure logging: https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

Given all your questions, I'd suggest you start with our samples rather than building your own. Get those working and understand the mechanics before you move own to your custom host.
