### ISSUE TITLE
RefreshTokenStore does not save updated JsonCode

### ISSUE THREAD

**Issue by samikoivupalo** [IdentityServer/IdentityServer3.EntityFramework#94]
When refresh token is updated, JsonCode needs to be updated too, because it contains LifeTime property that can be extended.

**Comment by brockallen** [comment]
Ok, I'll have a look when I can. Thx.

**Comment by philipbjorge** [comment]
@brockallen or @samikoivupalo -- Can you expand on this bug report?
I'm currently using this project for a reference implementation and would like to avoid a known bug...

**Comment by brockallen** [comment]
Yep, thanks for the nudge...

**Comment by brockallen** [comment]
Is this (https://github.com/IdentityServer/IdentityServer3.EntityFramework/commit/f0eb1095ff9aad33c7333f752cc99c88bdf3efdb) the change you're expecting @samikoivupalo?

**Comment by samikoivupalo** [comment]
Yes. That worked for me. Thanks.

**Comment by brockallen** [comment]
2.4.2 NuGet pushed with the fix
