### ISSUE TITLE
Entity Token uses MySQL keyword

### ISSUE THREAD

**Issue by xiongtec** [IdentityServer/IdentityServer3.EntityFramework#99]
Token has a property named Key which is a reserved keyword in MySQL.

**Comment by brockallen** [comment]
And?

**Comment by xiongtec** [comment]
Sorry forgot to mentioned that it throwing exception when I was using DropCreateDatabaseAlways initializer. The query would get mysql exception until I changed key to TokenKey.

**Comment by brockallen** [comment]
I guess I don't know enough about how EF and MySql work together to help.

**Comment by xiongtec** [comment]
hopefully anyone who is using your awesome framework and MySQL this will help them.

**Comment by brockallen** [comment]
And so do you have a solution to the problem?

**Comment by xiongtec** [comment]
Key renamed to TokenKey.

**Comment by brockallen** [comment]
Ah ok, now I understand -- you had to change the column mapping for the Key property. Did you do this by forking the code and doing a custom build, or did you introduce a custom DbContext and override the mapping behavior?

**Comment by xiongtec** [comment]
took source here https://github.com/Nicholi/IdentityServer3.EntityFramework.MySql and changed the key property because I was also having the timestamp issue earlier the week to.

**Comment by brockallen** [comment]
Ok, thanks for the info.
